server:
  port: 9000
  servlet:
    context-path: /estudismo/v1

spring:
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
